// AUTO-GENERADO por packages/server/scripts/parse-ao-dat.mjs
// Fuente: Dat/Quests.DAT del AO Libre. NO EDITAR A MANO.

export interface QuestDef {
  readonly id: number;
  readonly nombre: string;
  readonly desc: string;
  readonly requiredLevel: number;
  readonly npcs: ReadonlyArray<{ readonly npc: number; readonly amount: number }>;
  readonly objs: ReadonlyArray<{ readonly item: number; readonly amount: number }>;
  readonly rewardGld: number;
  readonly rewardExp: number;
  readonly rewardObjs: ReadonlyArray<{ readonly item: number; readonly amount: number }>;
}

export const QUESTS: Record<number, QuestDef> = {
  1: { id: 1, nombre: "Bichos molestos", desc: "Se ha reportado una plaga de molestos murcielagos en todo el territorio. Por favor mata a 3 de ellos para colaborar.", requiredLevel: 1, npcs: [{ npc: 500, amount: 3 }], objs: [], rewardGld: 100, rewardExp: 500, rewardObjs: [] },
  2: { id: 2, nombre: "Caceria de lobos", desc: "Se han reportado muchas muertes en los alrededores de la ciudad de Banderbill. La milicia ha hecho un llamado a la comunidad para intentar solucionar este problema. Debes matar 15 lobos y traerme sus pieles para recibir una recompensa.", requiredLevel: 2, npcs: [{ npc: 501, amount: 15 }], objs: [{ item: 414, amount: 15 }], rewardGld: 200, rewardExp: 1000, rewardObjs: [] },
  3: { id: 3, nombre: "Caceria salvaje", desc: "Willdon, el guardabosques, precisa controlar la sobrepoblacion de lobos y osos en las cercanias de Ullathorpe. Ayudalo a retomar el control y te recompensara...", requiredLevel: 5, npcs: [], objs: [{ item: 414, amount: 10 }, { item: 415, amount: 10 }], rewardGld: 1500, rewardExp: 2000, rewardObjs: [{ item: 238, amount: 1 }] },
  4: { id: 4, nombre: "Contra los muertos vivos", desc: "Ayuda por favor!! Una horda de zombies y esqueletos esta acechando mi granja... Por favor deshazte de ellos y te recompensare con parte de mis ganancias.", requiredLevel: 15, npcs: [{ npc: 502, amount: 10 }, { npc: 503, amount: 10 }], objs: [], rewardGld: 3000, rewardExp: 4500, rewardObjs: [{ item: 559, amount: 1 }] },
  5: { id: 5, nombre: "El peligroso Dorck", desc: "Selenna, una importante miembro del circulo de druidas del Imperio, se encuentra preocupada por el peligro que significan las malignas criaturas que habitan en el bosque de Dorck. Cualquier aventurero que asesine a los aracnidos Gigantes y orcos con sus Hachas, tendra una justa recompesa.", requiredLevel: 20, npcs: [{ npc: 510, amount: 10 }, { npc: 523, amount: 10 }], objs: [{ item: 3, amount: 10 }], rewardGld: 5000, rewardExp: 5000, rewardObjs: [{ item: 851, amount: 1 }] },
  6: { id: 6, nombre: "Justicia divina", desc: "Icaro, el pregonero de Banderbill, ha dictaminado una caceria furtiva de asesinos y bandidos debido a multiples actos ilicitos que los pobladores del imperio han sufrido. Trae sus cabezas y seras bien recompensado.", requiredLevel: 18, npcs: [{ npc: 531, amount: 10 }, { npc: 530, amount: 10 }], objs: [], rewardGld: 7000, rewardExp: 7000, rewardObjs: [{ item: 1003, amount: 1 }, { item: 404, amount: 1 }] },
  7: { id: 7, nombre: "Capricho del Rey", desc: "Los caprichos de Rey deben de ser cumplidos a rajatabla y nos ha pedido construir un anillo de bodas. Para ello necesitamos que nos ayudes matando a las diferentes razas de etogniles que yacen escondidos por aqui. Consigue lo solicitado y la recompensa sera tan grande como tu valentia.", requiredLevel: 25, npcs: [{ npc: 715, amount: 3 }, { npc: 716, amount: 3 }, { npc: 717, amount: 3 }], objs: [], rewardGld: 10000, rewardExp: 500000, rewardObjs: [{ item: 129, amount: 1 }, { item: 659, amount: 1 }] },
  8: { id: 8, nombre: "Sombras colosales", desc: "Sir Arthur es el protector del Reino y esta reclutando gente con agallas para mantener alejado de la superficie a los titanes que amenazan con salir y destruir todo a su paso. Consigue matarlos y obtendras la mayor de todas las recompensas.", requiredLevel: 40, npcs: [{ npc: 930, amount: 1 }, { npc: 933, amount: 3 }, { npc: 934, amount: 3 }], objs: [], rewardGld: 100000, rewardExp: 8000000, rewardObjs: [{ item: 1146, amount: 1 }, { item: 403, amount: 6 }] },
  9: { id: 9, nombre: "Espiritu Guerrero", desc: "Mithandrill es un elfo del bosque radicado en Arghal que no puede salir a recolectar moras por una constante amenaza de criaturas salvajes, asesinos y bandidos. Ayuda al elfo y seras recompensado con objetos y monedas.", requiredLevel: 25, npcs: [{ npc: 531, amount: 100 }, { npc: 530, amount: 100 }, { npc: 523, amount: 100 }], objs: [], rewardGld: 100000, rewardExp: 50000, rewardObjs: [{ item: 1138, amount: 1 }, { item: 532, amount: 1 }] },
  10: { id: 10, nombre: "Ojo por ojo", desc: "Orfeo, el huerfano, ha jurado vengar la muerte de sus padres y por ello a decidido entregar parte de su herencia a quienes maten las criaturas que asaltaron su ciudad.", requiredLevel: 25, npcs: [{ npc: 510, amount: 2000 }, { npc: 518, amount: 5 }, { npc: 542, amount: 2 }, { npc: 552, amount: 2 }], objs: [], rewardGld: 500000, rewardExp: 50000, rewardObjs: [{ item: 1134, amount: 1 }] },
  11: { id: 11, nombre: "Marcando un nuevo comienzo", desc: "Zhireles es un guerrero veterano de Gotland y hoy es su ultimo dia protegiendo estas tierras, ante tal suceso quiere dejar su ultima huella y para eso necesita que lo ayudes a matar 3 dragones legendarios que andan merodeando por estas tierras. Si logras hacerlo, Zhireles estara dispuesto a entregarte una maravillosa recompensa... Ademas, puedes contar con suerte y obtener gemas muy valiosas que poseen los dragones.", requiredLevel: 40, npcs: [{ npc: 798, amount: 1 }, { npc: 799, amount: 1 }, { npc: 800, amount: 1 }], objs: [{ item: 411, amount: 1 }, { item: 412, amount: 1 }, { item: 413, amount: 1 }], rewardGld: 80000, rewardExp: 12000000, rewardObjs: [{ item: 481, amount: 1 }, { item: 483, amount: 1 }] },
  12: { id: 12, nombre: "Un cazador en apuros.", desc: "Ayudame a controlar las plagas del bosque y te recompenzare!", requiredLevel: 15, npcs: [{ npc: 515, amount: 15 }, { npc: 510, amount: 15 }, { npc: 523, amount: 25 }, { npc: 506, amount: 150 }], objs: [], rewardGld: 15000, rewardExp: 15000, rewardObjs: [{ item: 664, amount: 15 }] },
  13: { id: 13, nombre: "Un mago en apuros.", desc: "Ayudame a controlar las plagas del bosque y te recompenzare!", requiredLevel: 15, npcs: [{ npc: 515, amount: 15 }, { npc: 510, amount: 15 }, { npc: 523, amount: 25 }, { npc: 506, amount: 100 }], objs: [], rewardGld: 15000, rewardExp: 15000, rewardObjs: [{ item: 37, amount: 5000 }, { item: 394, amount: 1 }] },
  14: { id: 14, nombre: "Bestias de las profundidades.", desc: "Temibles bestias estan aterrorizando a mi grupo de exploradores! Ayudame con ellas vere que seas recompenzado.", requiredLevel: 25, npcs: [{ npc: 706, amount: 5 }, { npc: 707, amount: 5 }], objs: [], rewardGld: 25000, rewardExp: 50000, rewardObjs: [{ item: 500, amount: 1 }, { item: 131, amount: 1 }, { item: 128, amount: 1 }, { item: 36, amount: 500 }] },
  15: { id: 15, nombre: "Un elfo embarrado.", desc: "Esta mancha de lodo que no se quita! Por favor ayudame con estas criaturas y vere que estes bien vestido.", requiredLevel: 30, npcs: [{ npc: 505, amount: 250 }, { npc: 611, amount: 100 }, { npc: 539, amount: 100 }, { npc: 534, amount: 50 }, { npc: 707, amount: 5 }], objs: [], rewardGld: 50000, rewardExp: 100000, rewardObjs: [{ item: 496, amount: 1 }] },
  16: { id: 16, nombre: "La energia de las islas.", desc: "La vida en esperanza esta sucumbiendo frente a terribles hechizos del mal. Por favor ayudame a recomponer el balance de las islas.", requiredLevel: 30, npcs: [{ npc: 551, amount: 50 }, { npc: 549, amount: 50 }, { npc: 513, amount: 50 }, { npc: 550, amount: 25 }, { npc: 706, amount: 5 }], objs: [], rewardGld: 50000, rewardExp: 100000, rewardObjs: [{ item: 536, amount: 1 }] },
  17: { id: 17, nombre: "Protector de las islas.", desc: "Una horda de deformidades malignas hace peligrar el balance natural de estas islas, por favor ayudame a restaurarlo.", requiredLevel: 30, npcs: [{ npc: 554, amount: 50 }, { npc: 511, amount: 25 }, { npc: 513, amount: 25 }, { npc: 537, amount: 10 }, { npc: 517, amount: 10 }], objs: [], rewardGld: 50000, rewardExp: 100000, rewardObjs: [{ item: 537, amount: 1 }, { item: 536, amount: 1 }] },
  18: { id: 18, nombre: "Peligros del mar abierto.", desc: "Cientos de navegantes estan siendo atacados por los mas peligrosos monstruos marinos. Sube a tu barca y ayudame con ellos. Prometo una paella y grandes recompensas al terminar.", requiredLevel: 30, npcs: [{ npc: 603, amount: 50 }, { npc: 621, amount: 50 }, { npc: 518, amount: 50 }, { npc: 606, amount: 25 }, { npc: 604, amount: 25 }], objs: [], rewardGld: 50000, rewardExp: 100000, rewardObjs: [{ item: 537, amount: 1 }] },
  19: { id: 19, nombre: "Huye cobarde!.", desc: "Por favor ayudame a salir de aqui! Esta oscuro y lleno de bichos feos, juro recompensarte!", requiredLevel: 25, npcs: [{ npc: 511, amount: 50 }, { npc: 554, amount: 50 }, { npc: 507, amount: 50 }, { npc: 543, amount: 5 }], objs: [], rewardGld: 50000, rewardExp: 150000, rewardObjs: [{ item: 37, amount: 1500 }, { item: 38, amount: 1500 }] },
  20: { id: 20, nombre: "Terrores de otros tiempos.", desc: "Espiritus de tiempos pasados acechan nuestro presente. Si aceptas esta mision deberas viajar y derrotarlos pero te aseguro que la recompensa valdra la pena.", requiredLevel: 38, npcs: [{ npc: 589, amount: 5 }, { npc: 609, amount: 5 }, { npc: 946, amount: 5 }, { npc: 796, amount: 5 }], objs: [], rewardGld: 250000, rewardExp: 250000, rewardObjs: [{ item: 1138, amount: 1 }, { item: 1134, amount: 1 }, { item: 1148, amount: 1 }] },
  21: { id: 21, nombre: "El coleccionista de huesos.", desc: "Este es un calabozo lleno de oscuras criaturas. Traeme sus sangres y asi podre hacerte algunas pocimas que te ayudaran en el camino.", requiredLevel: 35, npcs: [{ npc: 553, amount: 200 }, { npc: 550, amount: 100 }, { npc: 551, amount: 50 }, { npc: 517, amount: 25 }], objs: [], rewardGld: 250000, rewardExp: 250000, rewardObjs: [{ item: 37, amount: 10000 }, { item: 38, amount: 10000 }, { item: 36, amount: 2000 }, { item: 39, amount: 2000 }] },
  22: { id: 22, nombre: "En busca de las jaurias.", desc: "Jaurias de lobos atacan mis mineros por todo el mundo y pronto dejaremos de poder pagarle la cuota al rey. Necesitamos un viajero audaz que termine con estos lobos!", requiredLevel: 25, npcs: [{ npc: 501, amount: 100 }, { npc: 765, amount: 15 }, { npc: 703, amount: 15 }, { npc: 702, amount: 15 }, { npc: 766, amount: 15 }, { npc: 701, amount: 5 }], objs: [], rewardGld: 75000, rewardExp: 125000, rewardObjs: [{ item: 37, amount: 7000 }, { item: 38, amount: 5000 }, { item: 36, amount: 3000 }, { item: 39, amount: 2000 }] },
  23: { id: 23, nombre: "Todos a estribor!", desc: "El mundo entero cree que por que somos pocos somos un pueblo debil. ja! Traeme escamas de Leviatan y armare fuertes armaduras.", requiredLevel: 26, npcs: [{ npc: 548, amount: 200 }], objs: [], rewardGld: 125000, rewardExp: 250000, rewardObjs: [{ item: 403, amount: 1 }] },
  24: { id: 24, nombre: "Cava tu propia tumba.", desc: "Llevo mucho tiempo en el mercado negro de la muerte pero nunca antes me habian hecho un pedido de huesos tan grande. Ayudame a completar mi pedido y te pagare.", requiredLevel: 16, npcs: [{ npc: 598, amount: 20 }, { npc: 596, amount: 20 }, { npc: 599, amount: 20 }, { npc: 601, amount: 20 }, { npc: 600, amount: 10 }, { npc: 757, amount: 2 }], objs: [], rewardGld: 40000, rewardExp: 40000, rewardObjs: [{ item: 37, amount: 1500 }, { item: 38, amount: 1500 }, { item: 380, amount: 1 }] },
};
